---
- hosts : all
      become :
      tasks :
        - name: install JDK v17
          apt :
            name : openjdk-17-jdk
            state : present

- hosts : all
  become :
  tasks :
    - name: install JDK v17
      apt :
        name : openjdk-17-jdk
        state : present
    - name: java version
      shell: java --version
      register : ps
    - debug: var=ps.stdout_lines

- hosts : all
  become :
  tasks :
    - name: install JDK v17
      apt :
        name : openjdk-17-jdk
        state : present
    - name: java version
      shell: java --version
      register : ps
    - name : save the log to the output file
      local_action : copy content={{ps.stdout_lines}} dest=/etc/OutputLog
	