---
- hosts : all
  become : true
  tasks :
    - name : System date
      debug :
        var : ansible_date_time.date
    - name : System time
      debug :
        var : ansible_date_time.time
    - name : dynamic file with system timestamp
      file :
        path : /etc/testfile_{{ansible_date_time.date}}.log
        state : touch
        