---
- hosts : all
  become : true
  tasks :
    - name : create a file in a path
      file :
        path : /home/ubuntu/myfile2.txt
        state : touch
        
    - name : zip/archive single file
      archive :
        path : /home/ubuntu/myfile.txt
        dest : /home/ubuntu/myfile.zip
        format : zip
    - name : zip/archive multiple files
      archive :
        path :
          - /home/ubuntu/myfile.txt
          - /home/ubuntu/myfile2.txt
        dest : /home/ubuntu/multifilezip.zip
        format : zip
    - name : All folder zip/archive
      archive :
        path : /home/ubuntu
        dest : /home/ubuntu/allZip.zip
        format : zip